version: 1.0.{build}
image: Ubuntu2204

install:
  # appveyor's custom images are a pay-to-win feature; let's just clone the
  # setup and run it here each build :D
  # - git clone https://github.com/caffeine-storm/haunts-custom-build-image.git
  - export IMG=haunts-custom-build-image
  - export HASH=8b79106d85fc0a42cab2c8326815044ca73a4ede
  - wget https://github.com/caffeine-storm/$IMG/archive/$HASH.tar.gz -O $IMG.tar.gz
  - mkdir $IMG
  - tar -C $IMG --strip-components=1 -xf $IMG.tar.gz
  - sudo ./$IMG/install-build-dependencies.sh

build_script:
  - go build

test_script:
  - go test
